-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("dms ipc call notepad toggle"), { description = "dms ipc call notepad toggle" })
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"))
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("exec kcalc"))
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("exec dolphin"))
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("konsole"), { description = "ghostty" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("bash /home/jay/Documents/GitHub/dotfiles/rnd_bgnd_times_three.sh"))
hl.unbind("F11")
hl.bind("F11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle fullscreen" })
hl.unbind("SUPER + ALT + W")
hl.bind("SUPER + ALT + W", hl.dsp.group.toggle(), { description = "togglegroup" })
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle Floating" })
