-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-2", mode = "2560x1600@239.999", position = "6560x0", scale = 1, vrr = 1 })
hl.monitor({ output = "", mode = "preferred", position = "4000x0", scale = 1 })
hl.monitor({ output = "HDMI-A-2", mode = "2560x1440@59.951", position = "4512x936", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-1", mode = "3840x2160@59.997", position = "1440x648", scale = 1.25, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "2560x1440@59.951", position = "0x320", scale = 1, transform = 1, vrr = 0 })
