#!/bin/fish


# For monitor 1 (you can change the monitor number 1, 2, etc., depending on the monitor you want)
DISPLAY=:0 qdbus org.kde.plasmashell /org/kde/plasma/desktop /org/kde/plasma/desktop/Wallpaper org.kde.plasma.wallpaper.changeWallpaper "/home/jay/Downloads/A.jpg"

# For monitor 2 (if you have multiple monitors, you can change this to 2)
#DISPLAY=:0 qdbus org.kde.plasmashell /org/kde/plasma/desktop /org/kde/plasma/desktop/Wallpaper #org.kde.plasma.wallpaper.changeWallpaper "/path/to/your/wallpaper2.jpg"


